### ISSUE TITLE
Auction winners expect a "redeem" button like auction losers

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#121]
If a user loses an auction, the `REDEEM` button is easy to find on both the auction page and on the "my bids" page. However, auction winners may not realize that they need to `REGISTER` to get the change back from the second-highest bid. 

For auction winners, we can keep the REDEEM button on the page, and under the hood just send a REGISTER with null data `'{"records": []}'`. If a user has placed more than one bid (one of which is the winner) the usual REDEEM button could actually include this REGISTER output in the same transaction.

**Comment by smcki012** [comment]
This one caught me too. Won the auction for McKie/ (woo), but in the UI it gives me the option to both `Manage` the record and `Redeem` it still instead of calling it `Register` instead, which is the behavior I think most would benefit from as they can get those locked funds back in their wallet - then later send an update with an on-chain record like Matthew mentioned above. The `Redeem` button being there will surely lead to many think their wallet is bugged or their bid is irrecoverable when it actually is.

**Comment by rithvikvibhu** [comment]
I think this is already part of v0.6.2? There's a **Register** button next to all names that can be registered in **Your Bids** page.

Additionally, with PR #288, the Register button is available in the Auctions page and the Manage domain page.

**Comment by rithvikvibhu** [comment]
The register button is now available in the Your Bids page, Auction page, Manage Domain page, and as an action card on the Portfolio page.
