### ISSUE TITLE
[Feature] HNScan alternative

### ISSUE THREAD

**Issue by Falci** [kyokan/bob-wallet#152]
I had a look on the HNScan project and decided to run it on my node.
I'd like to configure it on Bob. When I click in a transaction, it should open in my custom HNScan.

**Comment by sdtsui** [comment]
Thanks for the suggestion @Falci .  Clarifying: you would _not_ like to be redirected to the website at hnscan.com, but your own locally hosted version?  Is this accurate?

If so, can you tell me a little more about why?  Just curious if it's for security features, if you're building something special, or anything else. :)
(Feel free to DM on Telegram if you prefer!)

**Comment by Falci** [comment]
> Clarifying: you would not like to be redirected to the website at hnscan.com, but your own locally hosted version? Is this accurate?
Yes, exactly.

Not a big deal, but running hnscan in my node is faster than the hnscan.com.

**Comment by pinheadmz** [comment]
This would be a cool setting. I've seen implementations in other Bitcoin applications, and basically there is just a text input field in settings where you can insert any URL and a `%s` placeholder for the txid. So for example, these would all be valid settings:

`https://hnscan.com/tx/%s`

`https://shakescan.com/transaction/%s`

`http://127.0.0.1:8080/tx/%s`

**Comment by brandondees** [comment]
Yeah I like this idea as well. hnscan.com is down / dead sometimes, and I sometimes prefer shakescan.com, or might want to run my own customized thing.

Tangentially related, it'd be extra cool to be able to register bob as a url handler for `hns://` or something so that other tools can link _into_ bob views as well. This would open the door to a lot of easy interop with other HNS tools (I'm specifically imagining exporting a namebase watchlist into bob with a single click, or navigating from any block explorer to the Bob bidding view for a name, or pre-populating HNS transfer details specified by the requester, etc.)
