### ISSUE TITLE
[Suggestion] Update to Latest Version without Re-Syncing

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#153]
As the chain grows, re-syncs will take much longer.  Currently, most users I've spoken to report >1hr sync times from first login to any interactivity.

I know we're working on API stuff which should make this much easier in the future, but I'd like to ask (@mslipper @pinheadmz @chikeichan) - how much work would it be to have a "save node state" option, where you can save a folder/config locally, and import a snapshot so the sync happens faster, or at least without a new full download?

**Comment by pinheadmz** [comment]
I think this should already be the case. Bob shouldn't need to resync when it's upgraded. I've encountered one user that had this issue and I think it was because they installed the upgrade as root and not as user (or vice versa) which meant the data directory went to a new location than the last version and Bob acted as though it was a brand new install. 

Also the sync time on OSX should be considerably faster because of the native crypto backend. Matt Slipper has issues getting that to build correctly on Windows and so the sync time on that platform will continue to be sub optimal for the current release.

**Comment by mslipper** [comment]
Yes, this is already the case. Only the wallet directory gets removed when users re-import; all chain state is preserved. Windows sync will remain slow until I can figure out how to get `bcrypto` to work on Windows.
