### ISSUE TITLE
[Feature] Support watch list import

### ISSUE THREAD

**Issue by brandondees** [kyokan/bob-wallet#178]
Watch list export is an option, but there's no support for the other direction. It would be really helpful for cases where I need clear my data and re-import, or bounce between different installs/versions while testing/troubleshooting/developing, or across different machines. Another important use case is to bring a name list from elsewhere, like namebase or other sources.

Some of my use cases would be nicely served if I could point bob to a txt file on disk to watch and update, and use a file sync tool to share it between machines. It'd be nice for me if other data and settings could also be managed that way.

**Comment by sdtsui** [comment]
Thank you, @brandondees .
What format are Namebase name lists in?

Because this is a fairly straightforward frontend feature (readfile, parse, add to local watchlist), I'm going to make this a suggested first issue for new contributors.

@-mention me here if you are interested in picking it up, and feel free to list some ideas around how you'd like to do it.
We can probably be helpful on UI suggestions, like where to put the upload button.
I'm willing to be pretty responsive on here to help grow the bob developer community, including pair programming.

**Comment by brandondees** [comment]
I have not yet dug into how namebase does it, as they don't have a UI-facing import/export feature, but they've mentioned planning to add bulk import/export features to the UI, and they endorse the use of their API even though it's not formally public/documented.

If/when I do find out, I'll be sure to mention here.

**Comment by rithvikvibhu** [comment]
Added in #258 and even linked, but wasn't closed by GitHub for some reason.
