### ISSUE TITLE
v0.5 issues testing with remote RPC

### ISSUE THREAD

**Issue by pinheadmz** [kyokan/bob-wallet#222]
In this story I installed master branch at 4f0df12af58ed662e7585e97f5b709ae6d40d20b and ran 'npm run dev'.
As soon as Bob starts up, I switch the network in the top right corner to regtest before doing anything else.

1) When I stop the internal node from settings, Bob appears to completely reset and asks me to set a new password and import a seed -- is the old wallet being wiped?

2) Entering custom RPC URL: I made the mistake of typing "`127.0.0.1:14039`" (wrong port and also no "http://") Bob endlessly tries to connect to something and can not be interrupted. Maybe I got impatient and there is a long timeout if the node doesn't respond. Unfortunately on reboot, Bob is endlessly stuck on "Loading node..." on the boot screen. So the whole wallet is bricked. I proceeded by deleting the data dir and starting over.

3) After starting over and getting the remote RPC URL correct (connecting to a local regtest hsd node) I noticed Bob was still in "mainnet" mode -- i.e. the receive address was `hs1...`. I couldn't find a way to switch Bob to regtest after selecting remote RPC (I thought I was already in regtest... see above). Even after a restart it seems like Bobs internal Allison wallet is still mainnet somehow even though the full node it's connected to is regtest. (**This probably should not be allowed to happen, at the hsd level**)

Can anyone help me test remote RPC with a regtest node?

**Comment by chikeichan** [comment]
For `1.`, this likely happen because the network type for `node` doesn't match . To make the UX more clear, I think i will make it in the future so that a new custrom rpc endpoint is added as `custom network` to the existing network type dropdown, where user can set the name of the saved custom rpc endpoint.

#254 includes a fix for:
2. a more detail custom rpc form 
3. a network switcher for custom rpc
