### ISSUE TITLE
[Feature-Request] Linux package of Bob wallet as flatpak 

### ISSUE THREAD

**Issue by anononez** [kyokan/bob-wallet#360]
I see many BTC devs implementing their wallet on flathub to gain adoption from Linux users 

https://flathub.org/apps/search/wallet

With flatpak package, we can run the app on many distros and architectures. I would love to see if Bob have plan to pack the app on flatpak.

Thank you.

**Comment by rithvikvibhu** [comment]
Bob has added AppImages to releases (just a few days) after this issue was created.
Was curious how flatpak differs from AppImage and found: https://github.com/AppImage/AppImageKit/wiki/Similar-projects#application-installation--execution

AppImage doesn't require root access to use, is already available on platforms like Ubuntu by default, is more decentralized and simpler in general.

Having said that, if you still want to build flatpaks, `electron-builder` has at least partial support for flatpaks: https://github.com/electron-userland/electron-builder/pull/5711 so it should be possible to edit `build.linux.target` and run `npm run package-linux`.

Lemme know how it goes!
