### ISSUE TITLE
Add Funds (aka: Handshake Worldwide Airdrop) shows incorrect reward amount

### ISSUE THREAD

**Issue by 0xdevalias** [kyokan/bob-wallet#425]
The 'Add Funds' (aka: Handshake Worldwide Airdrop) section of the app incorrectly states that you can claim `4,662.598321 HNS`, yet the official page states that it is only `4,264.994314 HNS`, and the amount I received appeared to only be `4246.894314 HNS`.

This leads to confusion for the end user, wondering why they didn't seem to receive the full amount.

## Expected Behavior
The app would correctly state that only `4,264.994314 HNS` (assuming the official docs are correct) or `4246.894314 HNS` (assuming the amount I received is correct) is claimable.

## Current Behavior
The app incorrectly states that `4,662.598321 HNS` is claimable.

This incorrect value can be seen at the following locations:

- https://github.com/kyokan/bob-wallet/blob/1dfd08a59e20fe69426837f789ba7bb869e4bca7/app/pages/GetCoins/index.js#L126
- https://github.com/kyokan/bob-wallet/blob/1dfd08a59e20fe69426837f789ba7bb869e4bca7/app/pages/GetCoins/index.js#L138-L140
- https://github.com/kyokan/bob-wallet/blob/1dfd08a59e20fe69426837f789ba7bb869e4bca7/app/pages/GetCoins/index.js#L181-L194

## Steps to Reproduce
1. Open app
2. Go to the 'Add Funds' page
3. Note that the incorrect value is shown
4. Compare this against the correct value listed at https://github.com/handshake-org/hs-airdrop#how-it-works

## Context (Environment)
N/A

## Logs
N/A

## Screencap
![image](https://user-images.githubusercontent.com/753891/140012036-94777c2a-ad00-4b70-8b00-73217c424589.png)

![image](https://user-images.githubusercontent.com/753891/140012018-36813407-cb51-4e4c-a5ca-0d8181530e29.png)

**Comment by pinheadmz** [comment]
4,246.994314 is the correct amount. This is probably easiest to see in build output of hs-airdrop:

https://github.com/handshake-org/hs-airdrop/blob/b7c92aea05ab6ac3d40f362bf5a6a4804f41e5d3/etc/tree.json#L11

You can also see this value in the faucet outputs of the airdrop:

https://github.com/handshake-org/hs-tree-data/blob/cca771405ab10e05a87ddc2e1426131e3f1642d9/proof.json#L1054

(There are 784 outputs with this value)

**Airdrops still pay miner fees!** That's why the amount you received was not this exact value. Using hs-airdrop a user can actually sign their airdrop proof with a custom fee amount (even 0 I suppose).

**Comment by 0xdevalias** [comment]
That makes sense RE: miner fees; I figured the smaller difference was likely something like that.

That means the amount currently listed I. This app is still wrong though.
