### ISSUE TITLE
how does the Exchange work?

### ISSUE THREAD

**Issue by Thijxx** [kyokan/bob-wallet#449]
There seems to be no documentation about the Exchange in Bob wallet.
Maybe I have listed a TLD, maybe not, I don't know.
What is this Submit button, what does Download do, why do I need to make an unsafe backup of things?
The Help button in Bob does not provide help, it contains the About and a link to this Bug Report page.

**Comment by rithvikvibhu** [comment]
It's an integration for Shakedex and connects to https://www.shakedex.com/

Code and explanation on how it works here: https://github.com/kurumiimari/shakedex

>why do I need to make an unsafe backup of things?

Because Shakedex keys are not derived from seed phrase (though there's a HIP for it). So it can't be restored from the seed phrase and requires a separate backup.

**Comment by Thijxx** [comment]
Thanks. I cancelled a listing and there is no information in Bob I think. On the listing overview it says 'cancelling' but on Portfolio it does not show what the status of the TLD is. When I start a listing it is very clear, it says Transferring domain and ready in 1 day and 6 hours but I think cancellation is not processed/shown there.

**Comment by rithvikvibhu** [comment]
The cancelling text needs work ig. But for reference, cancelling is also a transfer so needs 2 days, and then a finalize.

**Comment by Thijxx** [comment]
> The cancelling text needs work ig. But for reference, cancelling is also a transfer so needs 2 days, and then a finalize.

thanks!
