### ISSUE TITLE
Feature Request: Method to change storage location for blockchain download.

### ISSUE THREAD

**Issue by stephend9** [kyokan/bob-wallet#651]
I'm running the AppImage version on Linux on a machine with limited internal storage capacity. I would like a way to select where to store the Handshake blockchain that this app downloads. It starts downloading and fills up my hard drive space each time I try to get it working. 

## Expected Behavior
I'd like to be able to select an external SSD as the home for this file before it starts downloading for the first time.

## Current Behavior
The download goes somewhere on my boot drive and fills it up until my laptop grinds to a halt.

## Steps to Reproduce
1. Fill up your drive most of the way.
2. Run the AppImage and try to create a wallet.

## Context (Environment)
This issue has crashed my machine a few times. I'd simply like to be able to hold my TLDs on a self custody wallet instead of on a CEX.

Thanks for all the work so far creating this wallet and any help you're able to offer me. Go team HNS!

**Comment by rithvikvibhu** [comment]
There's an option for this already: Settings -> Network & Connection -> Data Directory.

1. Open Bob and set the new directory path in settings. This will not automatically move the data.
2. Close Bob
3. Move the `hsd_data` to the new location
4. Open Bob, it should use data from the new location.

Ex:
- Default data dir is `~/.config/Bob/hsd_data`
- If you change the path in settings to `/mnt/vol/hsd_data`,
- Make sure that the path `/mnt/vol/hsd_data` has the same `wallet`, `chain`, `blocks`, etc.

P.S. This will move blockchain data to another location, but Bob settings (like preferences and watching list) will still stay where it is currently. But that's not an issue since it takes up negligible space.

**Comment by stephend9** [comment]
Thanks so much for pointing this out. Sorry, I guess I missed it somehow. I'll give this a try and report back.

**Comment by rithvikvibhu** [comment]
Glad it's working!
