### ISSUE TITLE
Error while loading the Desktop App

### ISSUE THREAD

**Issue by rsriranga** [kyokan/bob-wallet#668]
Getting the follwoing error on the Desktop App (windows-11)

"Corruption: 11 missing files; e.g.: C:\Users\srira\AppData\Roaming\Bob\hsd_data\chain/3052975.ldb"

## Steps to Reproduce

1.
1.
1.
1.

**Comment by rithvikvibhu** [comment]
Resolved on Discord, but for future reference:

Database corruptions happen due to sudden shutdowns (typically because of power cuts).

If either `blocks`, `chain`, or `tree` dbs are corrupted, then all these 3 directories (contain blockchain data) must be deleted. This will make Bob start syncing again from 0%, but the wallets will still be present.

If the `wallet` db is corrupted, then the blockchain data can stay. Rename the `wallet` folder (effectively "deleting" it while keeping a backup) and start Bob. Import the wallets from seed / connect ledger. There is no need to download blockchain data, but a resync will be required to populate the wallet txs, domains, balance.
