### ISSUE TITLE
[Copy Change] "Mask" should say "Bid + Mask"?

### ISSUE THREAD

**Issue by sdtsui** [kyokan/bob-wallet#93]
![Screen Shot 2020-02-17 at 6 19 10 PM](https://user-images.githubusercontent.com/8230144/74698276-11a0c980-51b2-11ea-87f5-00557174167f.png)

I believe the last column on the right should say "Bid + Mask" not just Mask - I've placed a few bids now and just from looking at the transactions, it looks like either this column should say "Bid + Mask", or we should load subtract the bid amount before displaying.

WDYT, @mslipper @chikeichan ?

Please check on your end with bids you've placed: if this turns out to be a one-time bug, I'll try a few  more cases to repro.

**Comment by pinheadmz** [comment]
**In the `hsd` codebase the terms are:**
`bid`: a covenant/transaction type
`lockup`: the value of the TX output with the `BID` covenant
`value`: the secret amount of HNS the bidder thinks a name is worth
`blind`: the hash in the `BID` covenant that commits to the `value`, salted with a random `nonce`

So there is no technical term for the amount of HNS difference between `value` and `lockup` although Namebase is calling it an "Added Blind" (see screenshot below). Bob calls this value a "disguise" but I think we should try to match hsd and Namebase more closely.

So this table above could say `bid value` and `lockup` instead of `bid` and `mask`.

Then I think on the Send Bid screen, we _could_ think about switching "disguise" to "added blind" and "total mask" to "total lockup"...

thoughts @mslipper ?

![nb](https://user-images.githubusercontent.com/2084648/78364330-46fb4e00-758b-11ea-929d-3fd1e7773087.png)


![bob](https://user-images.githubusercontent.com/2084648/78364342-4a8ed500-758b-11ea-9589-4fb43709bd51.png)

**Comment by rithvikvibhu** [comment]
I agree with switching to Namebase's terminology as the majority of people new to Handshake will find Namebase first (thanks to the Learning Center, etc.) and then Bob.

This could cause some confusion for existing Bob users, so I feel this has to be changed as early as possible before more people start using Bob.

If everyone agrees, I'll add these changes to PR #290.
